require: rubocop-rspec

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 13

RSpec/ExampleLength:
  Max: 16

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 2
